# Generated by Django 3.1.2 on 2021-04-12 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0010_auto_20210402_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ImageField(default='none', upload_to='video/')),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.detail')),
            ],
        ),
    ]
