# Generated by Django 3.1.2 on 2021-04-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_video_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_no', models.IntegerField()),
                ('time', models.DecimalField(decimal_places=1, max_digits=4)),
                ('correct_form', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wrong_form', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
