# Generated by Django 3.1.2 on 2021-04-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='rep_no',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
