# Generated by Django 3.1.2 on 2021-04-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210413_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
