# Generated by Django 3.1.2 on 2021-04-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_stats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
