# Generated by Django 3.1.2 on 2021-04-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='exercise_id',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='session_id',
            new_name='session',
        ),
    ]
