# Generated by Django 3.1.2 on 2021-04-15 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210414_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
