# Generated by Django 3.1.2 on 2021-04-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_stats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
