# Generated by Django 3.1.2 on 2021-04-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_stats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
