# Generated by Django 3.1.2 on 2021-04-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
