# Generated by Django 3.1.2 on 2021-04-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_stats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
