# Generated by Django 3.1.2 on 2021-03-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20210323_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='exercises',
            new_name='Exercise',
        ),
    ]
