# Generated by Django 3.1.2 on 2021-03-24 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20210323_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='status',
            new_name='flair',
        ),
    ]
