# Generated by Django 3.1.2 on 2021-03-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_exercise_a_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTitle', models.CharField(max_length=25)),
                ('gif_1', models.ImageField(default='none', upload_to='images/')),
                ('gif_2', models.ImageField(default='none', upload_to='images/')),
                ('step_1', models.CharField(max_length=200)),
                ('step_2', models.CharField(max_length=200)),
                ('step_3', models.CharField(max_length=200)),
                ('step_4', models.CharField(max_length=200)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.exercise')),
            ],
        ),
    ]
