# Generated by Django 3.1.2 on 2021-03-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='subTitle',
        ),
    ]
