# Generated by Django 3.1.2 on 2021-03-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_remove_detail_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='title',
            field=models.CharField(default='none', max_length=25),
        ),
    ]
