# Generated by Django 3.1.2 on 2021-04-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_auto_20210402_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='a_image',
        ),
        migrations.AddField(
            model_name='detail',
            name='gif_2',
            field=models.ImageField(default='none', upload_to='gifs/'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='gif_1',
            field=models.ImageField(default='none', upload_to='gifs/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(upload_to='exercises/'),
        ),
    ]
