# Generated by Django 3.1.2 on 2021-04-15 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_auto_20210402_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise'),
        ),
    ]
